### ISSUE TITLE
Unable to connect to IRC server with TLS/SSL

### ISSUE THREAD

**Issue by valankar** [weechat/weechat-container#11]
It seems I need to turn tls_verify off to connect to for example irc.irchighway.net. Is there perhaps some missing TLS/SSL files in the docker image?

**Comment by flashcode** [comment]
Hi @valankar,

Which image are you using: debian, debian-slim, alpine, alpine-slim?

I tried with debian, works fine on irc.libera.chat server with TLS, so certificates are there.

For irchighway, it seems their certificate doesn't match the hostname as I have this error displayed:

```
 -- │ irc: connecting to server irc.irchighway.net/6697 (TLS)...
 -- │ gnutls: receiving 1 certificate
 -- │  - certificate[1] info:
 -- │    - subject `O=IRCHighway,ST=Some-State,C=FR', issuer `O=IRCHighway,ST=Some-State,C=FR', serial 0x57e010b20d30f65f920457ac4e8dafcc3427baa9, RSA key 2048 bits, signed using RSA-SHA256, activated `2021-12-07 16:36:16 UTC', expires `2031-12-05 16:36:16 UTC', pin-sha256="iyESdFe4gMYO/rk77V/kmK726pcz6JIwf+DuILPS5Hw="
=!= │ gnutls: the hostname in the certificate does NOT match "irc.irchighway.net"
=!= │ gnutls: peer's certificate is NOT trusted
=!= │ gnutls: peer's certificate issuer is unknown
=!= │ irc: TLS handshake failed
=!= │ irc: error: Error in the certificate.
```

I can reproduce this outside docker, so this seems to be an issue with this server.

**Comment by valankar** [comment]
Just the default image. Thanks for checking, seems it is indeed an issue with the server.
